export const THEMES = {
  'dark-blue': {
    name: 'Dark Blue',
    bgGradient: 'from-slate-950 via-slate-900 to-slate-800',
    navBg: 'from-slate-900 to-slate-800',
    sidebarBg: 'from-slate-900 to-slate-800',
    accentColor: 'from-blue-600 to-blue-700',
    accentHover: 'hover:bg-slate-700/50',
    sidebarBorder: 'border-slate-700',
    navBorder: 'border-slate-700',
  },
  'dark-indigo': {
    name: 'Dark Indigo',
    bgGradient: 'from-slate-950 via-indigo-950 to-indigo-900',
    navBg: 'from-indigo-900 to-indigo-800',
    sidebarBg: 'from-indigo-900 to-indigo-800',
    accentColor: 'from-indigo-600 to-indigo-700',
    accentHover: 'hover:bg-indigo-700/50',
    sidebarBorder: 'border-indigo-700',
    navBorder: 'border-indigo-700',
  },
  'dark-cyan': {
    name: 'Dark Cyan',
    bgGradient: 'from-slate-950 via-slate-900 to-slate-800',
    navBg: 'from-slate-900 to-slate-800',
    sidebarBg: 'from-slate-900 to-slate-800',
    accentColor: 'from-cyan-500 to-cyan-600',
    accentHover: 'hover:bg-cyan-700/50',
    sidebarBorder: 'border-cyan-700',
    navBorder: 'border-cyan-700',
  },
  'dark-emerald': {
    name: 'Dark Emerald',
    bgGradient: 'from-slate-950 via-slate-900 to-slate-800',
    navBg: 'from-slate-900 to-slate-800',
    sidebarBg: 'from-slate-900 to-slate-800',
    accentColor: 'from-emerald-600 to-emerald-700',
    accentHover: 'hover:bg-emerald-700/50',
    sidebarBorder: 'border-emerald-700',
    navBorder: 'border-emerald-700',
  },
  'light-clean': {
    name: 'Light Clean',
    bgGradient: 'from-slate-50 via-white to-slate-100',
    navBg: 'from-white to-slate-50',
    sidebarBg: 'from-slate-50 to-white',
    accentColor: 'from-blue-600 to-blue-700',
    accentHover: 'hover:bg-slate-100/50',
    sidebarBorder: 'border-slate-200',
    navBorder: 'border-slate-200',
    textColor: 'text-slate-900',
    textMuted: 'text-slate-600',
  },
  'dark-amber': {
    name: 'Dark Warm',
    bgGradient: 'from-slate-950 via-slate-900 to-slate-800',
    navBg: 'from-slate-900 to-slate-800',
    sidebarBg: 'from-slate-900 to-slate-800',
    accentColor: 'from-orange-500 to-amber-600',
    accentHover: 'hover:bg-orange-700/50',
    sidebarBorder: 'border-orange-700',
    navBorder: 'border-orange-700',
  },
};
